credentials:
  usernames:
    admin_user:
      name: "Administrateur"
      password: "<mot_de_passe_haché>"
      role: admin

cookie:
  name: streamlit_auth
  key: random_signature_key
  expiry_days: 1
